Loginlogout
shinonome-inc/backend-final-assignment-reika pull request #5
Opened 2024-06-16 09:49 UTC by reika011329

## 受講生の確認事項

- [ ] 画面をブラウザで実際に開いてテスト要件の[画面と機能](https://docs.google.com/spreadsheets/d/1tUi2xkohBzXZySmKDYruRruvlOmUV6bJK_GExeG5Tsw/preview)の動作確認をした（動作が分からない場合講師からスクリーンショットの提出を求めることがあります）
- [ ] 作成したモデルを全てDjango管理画面に登録した
- [ ] テスト要件のテストを全て実装した
- [ ] CI が全て通った

## １次レビュアーの確認事項

- [ ] [レビューポイント](https://www.notion.so/shinonome-inc/Backend-Wiki-fc6c2fb218fd42c8a5cb3abbea93a6bd?pvs=4#236ff7ed318e48648b3649782b101498)を満たしている

2024-06-17 10:33 UTC, TamanPG commented on accounts/views.py
> +class CustomLoginView(LoginView):
【参考(修正不要)】
LoginView, LogoutViewはurls.pyでの記載が推奨です

2024-06-18 01:18 UTC, TamanPG commented on accounts/urls.py
> +    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
auth_viewsを使う場合、views.pyのCustomLoginViewは表記不要です。

2024-06-19 23:47 UTC, TamanPG commented on templates/accounts/signup.html
> +<form method="POST">
この行はblock contentの中に入れてあげてください(signup.htmlの要素だと認識してくれないので)! それ以外はOKです👍

2024-06-24 10:08 UTC, gaato requested changes

2024-06-24 10:08 UTC, gaato commented on accounts/tests.py
> +        if response.context:
ここだけ他のテストケースと違うので統一させてください。
（そもそも `response.context` が `None` 以外の `False` に評価される値の場合はテストが通ってしまうので多分よくないです）

2024-06-24 10:08 UTC, gaato commented on accounts/tests.py
> +        response = self.client.get(reverse("accounts:login"))
せっかく `self.url` を定義しているので使いましょう。

2024-06-26 05:46 UTC, gaato requested changes

2024-06-26 05:46 UTC, gaato commented on tweets/views.py
> +        return object.user == self.request.user
これはログイン・ログアウト機能の PR なので他の機能の変更は含めないでください．今この変更をマージしてしまうと，ツイート機能のレビュー時にこの変更が見られなくなってしまいます．
（レビュー中に同時にやるのは良いのですが，別のブランチでやるようにお願いします．）

また，こういうときに戻しやすいようにコミットはもっと細かく分割して１つの変更に対して１つのコミットにすると良いです．今回は申し訳ないですが頑張って戻してください．

2024-06-30 10:04 UTC, gaato requested changes
コメントしてる途中に気づいたのですが多分これらの変更は
```
git restore --source=7c7ec275f1c6a4ca46f1da1d17c5f83360dc0c9f --worktree tweets/ templates/tweets/
```
というコマンドを打てば一発でできるはずです．

コマンドの解説：
- `git restore` 変更を打ち消すコマンド
- `--source=<commit-hash>` どこからの変更を打ち消すか指定する（今回は `main` ブランチが指すコミットを `git log` で探したらこれだった）
- `--worktree <directory-path>` 指定したディレクトリ以下に対して適用する

2024-06-30 10:04 UTC, gaato commented on tweets/forms.py
> +        fields = ("content",)
これを含めツイート機能に関わるすべての変更（ログイン・ログアウト機能に関係ない変更）は削除してください :pray:

2024-06-30 10:04 UTC, gaato commented on templates/tweets/create.html
> +{% endblock%}
ここも

2024-06-30 10:04 UTC, gaato commented on templates/tweets/delete.html
> +{% endblock %}
ここも

2024-06-30 10:04 UTC, gaato commented on templates/tweets/detail.html
> +{% endblock%}
ここも

2024-06-30 10:04 UTC, gaato commented on tweets/migrations/0001_initial.py
> +    ]
このファイルも削除お願いします．これ削除して migrate したら失敗するかもしれないですがそうなった時は一旦 `db.sqlite3` を削除して migrate し直せばいけるはずです．（`db.sqlite3` を削除するとデータベースの中身がすべて消えてしまうのですが，保持したまま修正するのは少し手間がかかるので削除でいいと思います）

2024-06-30 10:04 UTC, gaato commented on tweets/models.py
> +        return f"{self.user.username} - {self.content} ({self.time})"
これも削除お願いします

2024-06-30 10:04 UTC, gaato commented on tweets/tests.py
> +#    def test_failure_post_with_unliked_tweet(self):
このコメントアウトが微妙に変わっていて多分あとで苦労するので直しておいたほうが良いです．

2024-07-01 09:33 UTC, gaato approved these changes

2024-07-01 09:54 UTC, merged